# Generated by Django 2.2.4 on 2019-08-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='default-slug'),
            preserve_default=False,
        ),
    ]
