# Generated by Django 2.2.4 on 2019-08-14 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190813_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=256)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Gallery')),
            ],
        ),
    ]
