# Generated by Django 2.2.4 on 2019-08-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproject',
            name='technologies',
            field=models.CharField(default='some tech', max_length=512),
            preserve_default=False,
        ),
    ]
