# Generated by Django 2.2.4 on 2019-08-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_codingproject_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingproject',
            name='technologies',
            field=models.TextField(),
        ),
    ]
