# Generated by Django 2.2.4 on 2019-08-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190820_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
