# Generated by Django 2.2.4 on 2019-08-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190822_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codingproject',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='codingproject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
